from .word_controler import WordViewSet
from .gender_controller import GenderViewSet
from .case_controller import CaseViewSet
from .part_of_speech_controller import PartOfSpeechViewSet
from .word_number_controller import WordNumberViewSet
from .word_form_controller import WordFormViewSet
from .context_controller import ContextViewSet
from .context_word_form_pair_controller import ContextWordFormPairViewSet
