version: '3.9'

services:
  languagetrainer:
    container_name: LanguageTrainer
    build: .
    ports: 
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=languagetrainerdb
      - PG_PORT=5432
    depends_on:
      - languagetrainerdb
      
  languagetrainerdb:
    container_name: LanguageTrainerDb
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LanguageTrainerDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}