# Generated by Django 5.0.7 on 2024-07-22 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('base_form', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_trainer_app.gender')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_trainer_app.partofspeech')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('phrase_start', models.CharField(max_length=200)),
                ('valid_words', models.ManyToManyField(to='language_trainer_app.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('word_form', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_trainer_app.case')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_trainer_app.gender')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_trainer_app.word')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_trainer_app.wordnumber')),
            ],
        ),
    ]
