# Generated by Django 5.0.6 on 2026-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_trainer_app', '0003_create_teacher_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word',
        ),
        migrations.RemoveConstraint(
            model_name='wordform',
            name='unique_word_form',
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(condition=models.Q(('gender__isnull', False)), fields=('base_form', 'part_of_speech', 'gender'), name='unique_word_with_gender'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(condition=models.Q(('gender__isnull', True)), fields=('base_form', 'part_of_speech'), name='unique_word_without_gender'),
        ),
        migrations.AddConstraint(
            model_name='wordform',
            constraint=models.UniqueConstraint(condition=models.Q(('gender__isnull', False)), fields=('word', 'case', 'gender', 'number'), name='unique_word_form_with_gender'),
        ),
        migrations.AddConstraint(
            model_name='wordform',
            constraint=models.UniqueConstraint(condition=models.Q(('gender__isnull', True)), fields=('word', 'case', 'number'), name='unique_word_form_without_gender'),
        ),
    ]
