# Generated by Django 5.0.6 on 2026-04-06 00:00

from django.db import migrations


def add_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS language_trainer_word_base_form_trgm_idx "
        "ON language_trainer_app_word USING GIN (base_form gin_trgm_ops);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS language_trainer_word_form_trgm_idx "
        "ON language_trainer_app_wordform USING GIN (word_form gin_trgm_ops);"
    )


def remove_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP INDEX IF EXISTS language_trainer_word_form_trgm_idx;")
    schema_editor.execute(
        "DROP INDEX IF EXISTS language_trainer_word_base_form_trgm_idx;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("language_trainer_app", "0004_fix_word_wordform_null_gender_uniqueness"),
    ]

    operations = [
        migrations.RunPython(
            add_postgres_search_indexes,
            remove_postgres_search_indexes,
        ),
    ]
