# Generated by Django 5.0.6 on 2026-04-06 00:00

from django.db import migrations


def add_postgres_lower_exact_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS language_trainer_word_base_form_lower_idx "
        "ON language_trainer_app_word (LOWER(base_form));"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS language_trainer_word_form_lower_idx "
        "ON language_trainer_app_wordform (LOWER(word_form));"
    )


def remove_postgres_lower_exact_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP INDEX IF EXISTS language_trainer_word_form_lower_idx;")
    schema_editor.execute(
        "DROP INDEX IF EXISTS language_trainer_word_base_form_lower_idx;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("language_trainer_app", "0005_add_search_indexes"),
    ]

    operations = [
        migrations.RunPython(
            add_postgres_lower_exact_indexes,
            remove_postgres_lower_exact_indexes,
        ),
    ]