# Generated by Django 5.2.12 on 2026-04-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_trainer_app", "0006_add_lower_exact_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="animacy",
            field=models.CharField(
                blank=True,
                choices=[("Anim", "Одушевлённое"), ("Inan", "Неодушевлённое")],
                max_length=4,
                null=True,
            ),
        ),
    ]
