# Generated by Django 5.2.13 on 2026-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_trainer_app", "0007_add_word_animacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gender",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="partofspeech",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wordnumber",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
