from .gender import Gender
from .part_of_speech import PartOfSpeech
from .word_number import WordNumber
from .case import Case
from .word import Word
from .adjective import Adjective
from .word_form import WordForm
from .adjective_form import AdjectiveForm
from .phrase import Phrase
